version: '3.8'

services:
  granite-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: granite-4.0-api
    ports:
      - "8081:8080"
    environment:
      - LLAMA_THREADS=${LLAMA_THREADS:-96}
      - LLAMA_CONTEXT_SIZE=${LLAMA_CONTEXT_SIZE:-16384}
      - LLAMA_PORT=8080
      - LLAMA_HOST=0.0.0.0
    restart: unless-stopped
    volumes:
      # Persistent model storage (survives container restarts)
      - ./models:/app/models
      # Optional: logs directory for debugging
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits (optional, adjust based on needs)
    deploy:
      resources:
        limits:
          cpus: '96'
          memory: 16G
        reservations:
          cpus: '48'
          memory: 8G
